# backup of inference.yaml before switching to finetuned ckpt
# pretrained_model: lightning_logs/style_mvp/checkpoints/last.ckpt
pretrained_model: /data5/zhangjiening/Data_Generation/lightning_logs/style_mvp_adapter_5k/checkpoints/last.ckpt
config_file: configs/anydoor.yaml
save_memory: False
