Train:
  MIG_Sea:
    bg_dir: 
    masked_dir:
    fg_dir:
    mask_dir: 

Test:
  DreamBooth:
    fg_dir: path/DreamBooth/AnyDoor_DreamBooth
    bg_dir: path/DreamBooth/v1_800

  VitonHDTest:
    image_dir: path/TryOn/VitonHD/test/cloth



